#!/usr/bin/python3
# SPDX-FileCopyrightSPDX-FileCopyrightText: 2024 Kakeru Tanaka

import sys


ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
